#!/bin/zsh
# Profile file. Runs on login. Environmental variables are set here.

# Adds `~/.local/bin` to $PATH
#export PATH=":${$(find $HOME/.local/bin -type d -printf %p:)%%:}$PATH"
#export PATH=$PATH$(find $HOME/.local/bin -type d -printf ":%p")
export PATH="$HOME/.local/bin:$PATH"
# Cargo/rust shit
export PATH="$PATH:$XDG_CONFIG_HOME/cargo/bin"
export PATH="$PATH:$HOME/.cabal/bin:$HOME/.ghcup/bin"
. "/home/samsepi0l/.config/cargo/env"
# Firefox hardware decode
export MOZ_X11_EGL=1
export NO_AT_BRIDGE=1
export GHCUP_USE_XDG_DIRS=1
# Default programs:
export PAGER="most"
# Systemd is retarded and doesnt use normal pager variable :DDDDD
export SYSTEMD_PAGER="most"
export VISUAL="nvim"
export OPENER="xdg-open"
export EDITOR="nvim"
export TERMINAL="alacritty"
export TERMINAL_PROG="alacritty"
export BROWSER="librewolf"
#ibus (2 keyboard layouts)
#export GTK_IM_MODULE="ibus"
#export XMODIFIERS="@im=ibus"
#export QT_IM_MODULE="ibus"
#export SDL_IM_MODULE="ibus"
#export GLFW_IM_MODULE="ibus"
#most pager
export MOST_INITFILE="$HOME/.config/most/.mostrc"
#unreal engine .net cli tool telemetry turn off
export DOTNET_CLI_TELEMETRY_OPTOUT="true"
# ~/ Clean-up:
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export PYTHONSTARTUP="$HOME/.config/python/pythonrc.py"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_DATA_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1
