#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "${XINITRC}" ] && alias startx="startx $XINITRC"

[ -f "${MBSYNCRC}" ] && alias mbsync="mbsync -c $MBSYNCRC"

# Verbosity and settings that you pretty much just always are going to want.
alias \
 shellcheck="shellcheck -o all --enable all" \
 gitignored="git ls-files --others --ignored --exclude-standard" \
 space="df --type=xfs -h" \
 restart="sudo restart now" \
 debi="gdebi" \
 image="nsxiv" \
 unp="unp -U" \
 cp="cp -ivr" \
 mv="mv -iv" \
 la="ls -hN --color=auto --group-directories-first -a" \
 bc="bc -ql" \
 mkdir="mkdir -pv" \
 ffmpeg="ffmpeg -hide_banner" \
 shutdown="sudo shutdown now" \
 info="info --vi-keys"
# lf="lfub"
# Colorize commands when possible.
alias \
 ls="ls -hN --color=auto --group-directories-first" \
 grep="grep --color=auto" \
 diff="diff --color=auto" \
 ccat="highlight --out-format=ansi" \
 ip="ip -color=auto" \
#retarded wget rc history file in .cache
alias wget="wget --hsts-file=\"~/.config/wget-hsts\""
# Aliases
alias \
 la="lsd -a" \
 ls="lsd" \
 rm="rmw" \
 cd="z" \
 cdi="zi" \
 record="arecord -t wav -r 48000 -c 1 -f S16_LE recording.wav"
