#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. $HOME/.config/x11/xsession

#above was default config
#autostart
${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile
$HOME/.local/bin/remaps
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
exec awesome
