#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. "$HOME"/.config/x11/xsession

#above was default config
#autostart
"$HOME"/.config/shell/profile
"$HOME"/.local/bin/remaps
xrdb "$HOME"/.config/x11/xresources
exec awesome
