#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. /etc/X11/Xsession

#above was default config
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
#below, set wallpaper
exec "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile"
exec "/home/samsepi0l/.local/bin/remaps"
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
exec awesome
picom
