[profiles."example.com"]
user_id = "@saygo.2:tchncs.de"
[settings]
default_room = "@ronniehoney:matrix.org"
message_user_color = true
username_display = "localpart"
user_gutter_width = 9
[layout]
style = "restore"
[settings.notifications]
enabled = true
via = "desktop"
show_message = true
[macros."normal"]
";" = ":"
"u" = "\"+p"
"s" = "<C-w>m"
"mr" = ":reply<Enter>"
"mq" = ":cancel<Enter>y"
"mv" = ":editor<Enter>"
[settings.users]
"@saygo.2:tchncs.de" = { color = "none" }
"@ronniehoney:matrix.org" = { color = "red" }
"@toasterbirb:tchncs.de" = { color = "yellow" }
