[profiles."example.com"]
user_id = "@saygo.2:tchncs.de"
[layout]
style = "restore"
[settings]
default_room = "@ronniehoney:matrix.org"
message_user_color = true
username_display = "localpart"
user_gutter_width = 9
[settings.notifications]
enabled = true
[macros."normal"]
";" = ":"
"u" = "\"+p"
"s" = "<C-w>m"
"mr" = ":reply<Enter>"
"mq" = ":cancel<Enter>y"
"mv" = ":editor<Enter>"
